# Generated by Django 5.1.4 on 2025-01-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='type',
            field=models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('KW', 'KIWI'), ('PL', 'PLAIN'), ('EL', 'ELACHI')], default='ML', max_length=2),
        ),
    ]
