const joke = [
  `This is your captain speaking, AND THIS IS YOUR CAPTAIN SHOUTING.`,
  `I told my doctor that I broke my arm in two places – he told me to stop going to those places.`,
  `Before you criticize someone, walk a mile in their shoes. That way, when you do criticize them, you're a mile away, and you have their shoes.`,
  `I was at the park wondering why this frisbee kept getting bigger… and then it hit me.`,
  `Two fish in a tank, one looks at the other and says, "How do you drive this thing?"`,
  `Evening news is where they begin with “Good evening,” and then proceed to tell you why it isn’t.`,
  `When I met my now wife, I asked if she was vegetarian because she really loved animals. She responded, "No, I just really hate vegetables."`,
  `I know they say that money talks, but all mine says is “Goodbye.”`,
  `I have an inferiority complex, but it's not a very good one.`,
  `What do you call a lazy kangaroo? A pouch potato.`,
  `My wife and I laugh about how competitive we are. But I laugh more.`,
  `My wife told me to stop impersonating a flamingo. I had to put my foot down.`,
  `Have you heard about the guy who stole the calendar?! Well, he got 12 months!`,
  `Why did the ghost go to rehab? He was addicted to boos.`,
  `Why did the car get a flat tire? Because there was a fork in the road!`,
  `I stayed up all night and tried to figure out where the sun was. Then it dawned on me.`,
  `How did the hipster burn his mouth? He ate his pizza before it was cool.`,
  `What did the janitor say when he jumped out of the closet? SUPPLIES!!!!`,
  `Have you heard about the band 1023MB? It’s probably because they haven’t got a gig yet…`,
  `Why does the golfer wear two pants? Because he's afraid he might get a "Hole-in-one."`,
  `What's a pirate's favorite letter? (insert: you saying "R") You'd think it'd be the "R," but it's the "C."`,
  `What's the difference between a well-dressed cyclist and a scruffy guy on a tricycle? A tire.`,
  `Why should you wear glasses to maths class? Because it helps with division.`,
  `I'm so good at sleeping I can do it with my eyes closed!`,
  `Why does it take pirates so long to learn the alphabet? Because they could spend years at C.`,
  `Why did the woman go on the date with the mushroom? Because he was a fun-ghi.`,
  `Why do bananas never get lonely? Because they hang out in bunches.`,
  `What did the buffalo say when his kid went to college? Bison.`,
  `Why shouldn’t you tell secrets in a cornfield? Too many ears.`,
  `What do you call someone who doesn't like carbs? Lack-Toast Intolerant.`,
  `What does a nosey pepper do? Get jalapeno business.`,
  `A bear walks into a bar and says to the bartender, "I'll have a............ pint of beer please."`,
  `The bartender asks, "Why the big pause?"`,
  `The bear replies, "Well, I've always had 'em!"`,
  `Why did the can crusher quit his job? Because it was soda pressing.`,
  `Why did the birthday boy wrap himself in paper? He wanted to live in the present.`,
  `What does a house wear? A dress.`,
  `Why couldn't the toilet paper cross the road? Because it got stuck in a crack.`,
  `Why didn’t the bike want to go anywhere? Because it was two-tired!`,
  `Want to hear a pizza joke? Nahhh, it's too cheesy!`,
  `Why are chemists great at solving problems? Because they have all of the solutions!`,
  `Why is it impossible to starve in the desert? Because of all the sand which is there!`,
  `A string walks into a bar and the bartender goes, "Sorry, we don't serve strings here."`,
  `The string walks out all sad and defeated, then has a great idea. He ties himself in a bow, cuts off his ends to look all pretty, and struts back into the bar.`,
  `The bartender looks at him and goes, "Hey, aren't you that string I turned away before?" and the string goes, "Nope! I'm a frayed knot!"`,
  `What did the cheese say when it looked in the mirror? Halloumi!`,
  `Why did the developer go broke? Because he used up all his cache.`,
  `A man goes to the zoo. There's only ONE exhibit in the entire zoo. It was a Shih Tzu.`,
  `Did you know that ants are the only animals that don't get sick? It's true! It's because they have little antibodies.`,
  `Two antennas decided to get married, the ceremony was pretty boring, but the reception was great!`,
  `Why did the donut go to the dentist? To get a filling.`,
  `What do you call a bear with no teeth? A gummy bear!`,
  `Two friends are walking down the street thinking of something to do. One friend turns to the other and says, "Let's go get a drink, there's this new place that does THE best punch you'll ever drink."`,
  `So they make their way to the bar and walk straight up to the bartender "Bartender, two glasses of your best punch please."`,
  `The bartender replies in a stern voice, "If you want some punch you're gonna have to get in line like everybody else."`,
  `The friends turn and look around but there's no punch line… `,
  `What does a vegan zombie like to eat? Graaains.`,
  `What do you call a dinosaur with only one eye? A Do-you-think-he-saw-us!`,
  `Assistant: So what dimensions do the doors, hinges, walls, and locks need to be so that it all fits?`,
  `The person who invented public bathroom stalls: Can't stress how unimportant that part is`,
  `Why should you never fall in love with a tennis player? Because to them... love means NOTHING!`,
  `What did the full glass say to the empty glass? You look drunk.`,
  `What’s a potato’s favorite form of transportation? The gravy train`,
  `What did one ocean say to the other? Nothing, they just waved.`,
  `What did the right eye say to the left eye? Honestly, between you and me something smells.`,
  `What do you call a dog that's been run over by a steamroller? Spot!`,
  `Why it is hard for a communist to tell a joke? It's not funny until everyone gets it.`,
  `What's the difference between a hippo and a zippo? One's pretty heavy and the other's a little lighter`,
  `Little Johnny: "No... I just feel bad that you're standing alone..."`,
  `Why don't scientists trust Atoms? They make up everything.`,
  `Two whales walk into a pub.`,
  `They take a seat at the bar and the first one turns to the bartender and says: “Whhhhhoooooaaaaaeeeeeyyyyiiiiiaaaalllllllooooaaaaauuu?”`,
  `The second one turns to the first and says, “Shut up Fred, you’re drunk.”`,
  `Knock knock. (Who’s there?) Déja. (Déja who?) Knock knock.`,
  `Knock knock. (Who's there?) To (To who?) It's "to whom."`,
  `Knock knock. (Who's there?) Doorbell repair man.`,
  `Knock knock. (Who's there?) You. (You who?) Yoo-hoo! Anybody home?`,
  `Why don’t we see elephants hiding in trees? Because they’re really good at it.`,
  `Why does a Chicken Coop only have two doors? Because if it had four, it'd be a Chicken Sedan!`,
  `How do you find Will Smith in the snow? Look for the "Fresh Prints."`,
  `Can a kangaroo jump higher than a house? Of course. A house doesn’t jump at all!`,
  `What do diapers and politicians have in common? They both stink and need to be changed often.`,
  `A man walks into a bar, and it's empty - it's just him and the bartender. He sits down and orders a drink. `,
  `Why does Snoop Dogg use an umbrella? Fo drizzle.`,
  `If Bert Newton was a butcher...how would he introduce his wife? Meat Patty!`,
  `What do you call Batman when he skips church? Christian Bale.`,
  `What kind of pants do Mario and Luigi wear? Denim-denim-denim`,
  `Why can't Chuck Norris use the internet? Because he won't submit.`,
  `How does Lady Gaga like her steak? (sing) Raw-raw-raw-ra-ah-aww`,
  `What's Forrest Gump's email password? 1forrest1`,
  `Did you know that the urge to sing "The Lion Sleeps Tonight" is only ever a whim away? A whim away... a whim away…`,
  `Why didn’t the Terminator upgrade to Windows 10? I asked him and he said, “I still love vista, baby.”`,
];

const totalJokes = joke.length;

const tellJoke = ()=>{
    let jokeNum = Math.floor(Math.random() * totalJokes-1)

    const jokePara = document.querySelector('#jokePara')
    let jokeContent = joke[jokeNum]
    jokePara.innerHTML = `${jokeContent}`
}

const btn = document.querySelector('#playJoke')
btn.addEventListener('click', tellJoke)